# Generated by Django 5.0.1 on 2024-03-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoVeiculo',
            fields=[
                ('id_grupo_veiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao_grupo', models.CharField(max_length=250)),
                ('valor_mensal', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
