# Generated by Django 5.0.1 on 2024-03-27 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='situacao',
            field=models.BooleanField(default=True),
        ),
    ]
