# Generated by Django 5.0.1 on 2024-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_veiculo_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id_unidade', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_unidade', models.IntegerField(unique=True)),
                ('sigla_unidade', models.TextField(max_length=10)),
                ('descricao_unidade', models.TextField(max_length=100)),
            ],
        ),
    ]
