# Generated by Django 5.0.1 on 2024-04-03 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_veiculo_placa'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='veiculo',
            name='constraint_placa_unique',
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='unidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.unidade'),
        ),
    ]
