# Generated by Django 5.0.1 on 2024-04-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indisponibilidade',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='indisponibilidade',
            name='tem_reserva',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indisponibilidade',
            name='apontamento_reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locacao.apontamentoreserva'),
        ),
    ]
