# Generated by Django 5.0.1 on 2024-04-21 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0002_indisponibilidade_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indisponibilidade',
            name='apontamento_reserva',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locacao.apontamentoreserva'),
        ),
        migrations.AlterField(
            model_name='indisponibilidade',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='indisponibilidade',
            name='valor_base_veiculo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='indisponibilidade',
            name='valor_indisponibilidade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
