# Generated by Django 5.0.1 on 2024-04-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0003_alter_indisponibilidade_apontamento_reserva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indisponibilidade',
            name='id_indisponibilidade',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
