# Generated by Django 5.0.1 on 2024-04-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacao', '0004_alter_indisponibilidade_id_indisponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apontamentoreserva',
            name='id_apontamento_reserva',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
